(() => {
  const brl = n => n.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
  const months = ['Junho', 'Julho', 'Agosto'];
  const icon = {
    dashboard:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>',
    personal:'<svg viewBox="0 0 24 24"><circle cx="12" cy="7" r="4"/><path d="M4 21c.9-5.1 3.7-7.4 8-7.4s7.1 2.3 8 7.4"/></svg>',
    business:'<svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3M3 12h18M10 12v2h4v-2"/></svg>',
    reports:'<svg viewBox="0 0 24 24"><path d="M4 20V11h4v9M10 20V4h4v16M16 20v-7h4v7"/></svg>',
    wallet:'<svg viewBox="0 0 24 24"><path d="M4 6.5h14a2 2 0 0 1 2 2V19H4a2 2 0 0 1-2-2V6.5a2 2 0 0 1 2-2h12"/><path d="M15 11h7v5h-7a2.5 2.5 0 0 1 0-5z"/></svg>',
    up:'<svg viewBox="0 0 24 24"><path d="m5 15 6-6 4 4 5-6M15 7h5v5"/></svg>',
    down:'<svg viewBox="0 0 24 24"><path d="m5 9 6 6 4-4 5 6M15 17h5v-5"/></svg>',
    target:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.5"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>'
  };

  const css = `
  .ezapp{--p:#a64cf4;--pd:#7919ca;--ps:#f1e2ff;--ink:#17172b;--muted:#7d8593;--line:#e5e7ec;position:relative;height:100%;overflow:hidden;background:#fff;color:var(--ink);font-family:'DM Sans',sans-serif;isolation:isolate;user-select:none}.ezapp *{box-sizing:border-box}.ezapp button{font:inherit}.ez-page{height:100%;overflow:hidden;padding:25px 9px 40px;background:#fff}.ezapp[data-hero="1"] .ez-page{padding:22px 17px 54px}.ez-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px}.ez-head h3{margin:0;font-size:11px;font-weight:700;letter-spacing:-.02em}.ez-head p{margin:2px 0 0;color:var(--muted);font-size:6px}.ez-avatar{display:grid;width:26px;height:26px;place-items:center;border-radius:50%;background:var(--ps);color:var(--pd);font-size:7px;font-weight:800}.ezapp[data-hero="1"] .ez-head h3{font-size:15px}.ezapp[data-hero="1"] .ez-head p{font-size:8px}.ezapp[data-hero="1"] .ez-avatar{width:35px;height:35px;font-size:9px}
  .ez-toolbar{display:flex;align-items:center;justify-content:space-between;margin:7px 0}.ez-month{display:flex;align-items:center;gap:4px}.ez-month button{display:grid;width:22px;height:22px;place-items:center;border:1px solid var(--line);border-radius:7px;background:#fff;color:#727b89;cursor:pointer}.ez-month span{min-width:66px;text-align:center;font-size:6.3px;font-weight:700}.ez-new{display:flex;align-items:center;gap:3px;border:0;border-radius:7px;background:var(--p);padding:6px 8px;color:#fff;font-size:5.7px;font-weight:700;cursor:pointer}.ez-new svg{width:8px;height:8px}.ezapp svg{fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.ezapp[data-hero="1"] .ez-month button{width:29px;height:29px}.ezapp[data-hero="1"] .ez-month span{min-width:90px;font-size:8.5px}.ezapp[data-hero="1"] .ez-new{padding:8px 11px;font-size:7.5px}
  .ez-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.ez-stat{position:relative;min-width:0;border:1px solid var(--line);border-radius:9px;background:#fff;padding:7px;box-shadow:0 3px 10px #20163308}.ez-stat span{display:block;padding-right:17px;color:#737b89;font-size:5.2px;white-space:nowrap}.ez-stat strong{display:block;margin-top:3px;font-size:8.5px;white-space:nowrap}.ez-stat i{position:absolute;top:6px;right:6px;display:grid;width:17px;height:17px;place-items:center;border-radius:6px;background:var(--ps);color:var(--p)}.ez-stat svg{width:9px;height:9px}.ez-stat.income strong,.positive{color:var(--p)}.ez-stat.expense strong,.negative{color:#ef474c}.ez-stat.blue strong{color:#4f8ef7}.ezapp[data-hero="1"] .ez-stats{gap:8px}.ezapp[data-hero="1"] .ez-stat{padding:10px;border-radius:12px}.ezapp[data-hero="1"] .ez-stat span{font-size:7px}.ezapp[data-hero="1"] .ez-stat strong{font-size:12.5px}.ezapp[data-hero="1"] .ez-stat i{width:23px;height:23px}.ezapp[data-hero="1"] .ez-stat svg{width:12px;height:12px}
  .ez-card{margin-top:6px;border:1px solid var(--line);border-radius:10px;background:#fff;padding:7px}.ez-card-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:5px}.ez-card-head b{font-size:6.7px}.ez-card-head button{border:0;background:transparent;color:var(--p);font-size:5.2px;font-weight:700;cursor:pointer}.ezapp[data-hero="1"] .ez-card{margin-top:9px;padding:10px;border-radius:13px}.ezapp[data-hero="1"] .ez-card-head b{font-size:9px}.ezapp[data-hero="1"] .ez-card-head button{font-size:7px}.ez-forecast{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px}.ez-forecast div{min-width:0;border-radius:7px;background:#f7f7fa;padding:5px}.ez-forecast span{display:block;color:#858c99;font-size:4.6px}.ez-forecast strong{display:block;margin-top:2px;font-size:6.2px;white-space:nowrap}.ezapp[data-hero="1"] .ez-forecast div{padding:8px}.ezapp[data-hero="1"] .ez-forecast span{font-size:6.3px}.ezapp[data-hero="1"] .ez-forecast strong{font-size:8.7px}
  .ez-chart{position:relative;height:67px}.ez-chart svg{width:100%;height:100%;overflow:visible}.ez-gridline{stroke:#eff0f4;stroke-width:1}.ez-area{fill:url(#ezGradient)}.ez-line{fill:none;stroke:var(--p);stroke-width:2.1}.ez-line.exp{stroke:#ef5b67;stroke-width:1.6;stroke-dasharray:3 3}.ez-dot{fill:var(--p);stroke:#fff;stroke-width:1.4;cursor:pointer}.ez-labels{display:flex;justify-content:space-between;margin-top:-2px;color:#9aa0aa;font-size:4.4px}.ez-tip{position:absolute;z-index:2;top:1px;right:1px;border-radius:5px;background:#19192f;padding:3px 5px;color:#fff;font-size:4.8px}.ezapp[data-hero="1"] .ez-chart{height:105px}.ezapp[data-hero="1"] .ez-labels{font-size:6.3px}.ezapp[data-hero="1"] .ez-tip{font-size:7px}
  .ez-tabs{display:flex;gap:3px;margin:7px 0}.ez-tabs button{flex:1;border:1px solid var(--line);border-radius:7px;background:#fff;padding:5px 2px;color:#777f8e;font-size:5.5px;cursor:pointer}.ez-tabs button.on{border-color:var(--p);background:var(--p);color:#fff;font-weight:700}.ezapp[data-hero="1"] .ez-tabs button{padding:7px;font-size:7.3px}
  .ez-list{display:flex;flex-direction:column;gap:4px}.ez-row{display:flex;width:100%;align-items:center;gap:5px;border:1px solid var(--line);border-radius:8px;background:#fff;padding:5px;text-align:left;color:var(--ink);cursor:pointer}.ez-row-icon{display:grid;width:20px;height:20px;flex:0 0 auto;place-items:center;border-radius:6px;background:var(--ps);color:var(--p);font-size:5.8px;font-weight:800}.ez-row-copy{min-width:0;flex:1}.ez-row-copy b,.ez-row-copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ez-row-copy b{font-size:5.9px}.ez-row-copy small{margin-top:1px;color:#89909d;font-size:4.8px}.ez-row-value{font-size:5.8px;font-weight:700;white-space:nowrap}.ezapp[data-hero="1"] .ez-row{padding:7px}.ezapp[data-hero="1"] .ez-row-icon{width:27px;height:27px;font-size:8px}.ezapp[data-hero="1"] .ez-row-copy b,.ezapp[data-hero="1"] .ez-row-value{font-size:8px}.ezapp[data-hero="1"] .ez-row-copy small{font-size:6.3px}
  .ez-goal{border:1px solid var(--line);border-radius:9px;background:#fff;padding:7px;cursor:pointer}.ez-goal+.ez-goal{margin-top:5px}.ez-goal-top{display:flex;align-items:center;justify-content:space-between}.ez-goal b,.ez-goal strong{font-size:6.2px}.ez-goal strong{color:var(--p)}.ez-goal p{margin:2px 0 5px;color:#858c99;font-size:4.8px}.ez-progress{height:4px;overflow:hidden;border-radius:99px;background:#eeeef2}.ez-progress i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--p),#ca79ff)}
  .ez-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px}.ez-kpi{border-radius:7px;background:#f7f7fa;padding:5px}.ez-kpi span{display:block;color:#7e8694;font-size:4.6px}.ez-kpi strong{display:block;margin-top:2px;font-size:6.3px}.ez-warning{margin-top:5px;border:1px solid #ffd3ac;border-radius:6px;background:#fff9f2;padding:4px;color:#a9692f;font-size:4.5px}.ezapp[data-hero="1"] .ez-kpi{padding:8px}.ezapp[data-hero="1"] .ez-kpi span{font-size:6px}.ezapp[data-hero="1"] .ez-kpi strong{font-size:8px}
  .ez-bars{display:flex;height:75px;align-items:flex-end;gap:5px;padding:8px 3px 12px}.ez-bar{position:relative;display:flex;height:100%;flex:1;align-items:flex-end;justify-content:center;gap:2px;border:0;background:transparent;cursor:pointer}.ez-bar i{width:30%;border-radius:3px 3px 1px 1px}.ez-bar .in{background:linear-gradient(#c77dff,var(--p))}.ez-bar .out{background:linear-gradient(#ff91a2,#ed566c)}.ez-bar small{position:absolute;bottom:-11px;color:#9299a5;font-size:4.3px}.ez-bar.selected:after{content:attr(data-tip);position:absolute;top:-8px;border-radius:4px;background:#19192f;padding:2px 4px;color:#fff;font-size:4.3px;white-space:nowrap}.ez-legend{display:flex;justify-content:center;gap:8px;color:#818896;font-size:4.6px}.ez-legend i{display:inline-block;width:5px;height:5px;margin-right:2px;border-radius:50%}.ez-legend .purple{background:var(--p)}.ez-legend .red{background:#ed566c}.ezapp[data-hero="1"] .ez-bars{height:118px}.ezapp[data-hero="1"] .ez-bar small,.ezapp[data-hero="1"] .ez-legend{font-size:6px}
  .ez-nav{position:absolute;z-index:4;right:7px;bottom:6px;left:7px;display:flex;height:31px;border:1px solid var(--line);border-radius:10px;background:#fffc;box-shadow:0 6px 18px #19193014;backdrop-filter:blur(8px)}.ez-nav button{display:flex;min-width:0;flex:1;align-items:center;justify-content:center;flex-direction:column;gap:1px;border:0;background:transparent;color:#8c94a2;font-size:4.6px;cursor:pointer}.ez-nav button.on{color:var(--p);font-weight:700}.ez-nav svg{width:10px;height:10px}.ezapp[data-hero="1"] .ez-nav{right:14px;bottom:11px;left:14px;height:42px}.ezapp[data-hero="1"] .ez-nav button{font-size:6.3px}.ezapp[data-hero="1"] .ez-nav svg{width:14px;height:14px}
  .ez-toast{position:absolute;z-index:12;right:10px;bottom:43px;left:10px;border-radius:8px;background:#19192f;padding:6px;color:#fff;text-align:center;font-size:5.3px;box-shadow:0 8px 22px #0003}.ezapp[data-hero="1"] .ez-toast{right:17px;bottom:59px;left:17px;padding:9px;font-size:8px}.ez-modal-backdrop{position:absolute;z-index:9;inset:0;display:grid;place-items:end center;background:#1d15365c;padding:9px}.ez-modal{width:100%;border-radius:13px;background:#fff;padding:10px;box-shadow:0 -10px 28px #25183b2e}.ez-modal-head{display:flex;align-items:center;justify-content:space-between}.ez-modal-head b{font-size:7px}.ez-modal-head button{display:grid;width:20px;height:20px;place-items:center;border:0;border-radius:6px;background:#f3f3f6;color:#727988}.ez-modal-head svg{width:10px;height:10px}.ez-field{margin-top:6px}.ez-field label{display:block;margin-bottom:2px;color:#737b89;font-size:5px}.ez-field div{border:1px solid var(--line);border-radius:6px;padding:6px;font-size:6px}.ez-save{width:100%;margin-top:7px;border:0;border-radius:7px;background:var(--p);padding:6px;color:#fff;font-size:6px;font-weight:700}.ezapp{touch-action:manipulation}
  `;

  const head = (title, sub) => `<div class="ez-head"><div><h3>${title}</h3><p>${sub}</p></div><span class="ez-avatar" title="Lucas">LU</span></div>`;
  const toolbar = s => `<div class="ez-toolbar"><div class="ez-month"><button data-month="-1" aria-label="Mês anterior">‹</button><span>${months[s.month]} de 2026</span><button data-month="1" aria-label="Mês seguinte">›</button></div><button class="ez-new" data-action="new">${icon.plus} Novo</button></div>`;
  const stat = (label,value,tone='',which='wallet') => `<div class="ez-stat ${tone}"><span>${label}</span><strong>${value}</strong><i>${icon[which]}</i></div>`;
  const nav = active => `<nav class="ez-nav" aria-label="Navegação da demonstração">${[['dashboard','Início'],['personal','Pessoal'],['business','Negócio'],['reports','Relatórios']].map(([id,label])=>`<button data-view="${id}" class="${active===id?'on':''}" aria-label="Abrir ${label}">${icon[id]}<span>${label}</span></button>`).join('')}</nav>`;
  const rows = list => `<div class="ez-list">${list.map(x=>`<button class="ez-row" data-row="${x[1]}"><span class="ez-row-icon">${x[0]}</span><span class="ez-row-copy"><b>${x[1]}</b><small>${x[2]}</small></span><strong class="ez-row-value ${x[3][0]==='+'?'positive':'negative'}">${x[3]}</strong></button>`).join('')}</div>`;

  function chart(s){
    const incoming=[[1700,2200,1900,2750,2450,3200],[1900,2450,2150,3020,2680,3650],[2100,2680,2360,3280,2960,4300]][s.month], outgoing=[1180,1430,1540,1710,1890,2140];
    const pts=a=>a.map((v,i)=>[7+i*45.2,59-v/4700*48]), path=p=>p.map((x,i)=>`${i?'L':'M'}${x[0].toFixed(1)} ${x[1].toFixed(1)}`).join(' '), p=pts(incoming), q=pts(outgoing);
    return `<div class="ez-chart"><svg viewBox="0 0 240 66" preserveAspectRatio="none"><defs><linearGradient id="ezGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#a64cf4" stop-opacity=".22"/><stop offset="1" stop-color="#a64cf4" stop-opacity="0"/></linearGradient></defs><path class="ez-gridline" d="M7 18H233M7 36H233M7 54H233"/><path class="ez-area" d="${path(p)} L233 59 L7 59Z"/><path class="ez-line" d="${path(p)}"/><path class="ez-line exp" d="${path(q)}"/>${p.map((x,i)=>`<circle class="ez-dot" data-chart="${brl(incoming[i])}" cx="${x[0]}" cy="${x[1]}" r="2.7"/>`).join('')}</svg><div class="ez-labels"><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span></div></div>`;
  }

  function dashboard(s){const balance=[7480,7960,8420][s.month], inc=[5800,6100,6500][s.month], out=[3820,3440,3260][s.month];return `${head('Olá, Lucas!','Visão geral das suas finanças')}${toolbar(s)}<div class="ez-stats">${stat('Saldo atual',brl(balance),'','wallet')}${stat('Recebido no mês',brl(inc),'income','up')}${stat('Gasto no mês',brl(out),'expense','down')}${stat('Economia do mês',brl(inc-out),'blue','target')}</div><section class="ez-card"><div class="ez-card-head"><b>Previsão de caixa</b><button data-action="details">Ver detalhes</button></div><div class="ez-forecast"><div><span>A receber</span><strong class="positive">R$ 1.250</strong></div><div><span>A pagar</span><strong class="negative">R$ 980</strong></div><div><span>Projetado</span><strong class="positive">R$ 8.690</strong></div></div></section><section class="ez-card"><div class="ez-card-head"><b>Evolução do saldo</b><button data-view="reports">Relatório completo</button></div>${chart(s)}</section>`}

  function personal(s){
    if(s.mode==='goals') return goals(s);
    const all=[['SA','Salário','Hoje, 08:20','+ R$ 4.300'],['FR','Freelance','Ontem, 16:40','+ R$ 1.250'],['SU','Supermercado','Ontem, 18:42','- R$ 286'],['AL','Aluguel','05 ago','- R$ 980']], filtered=s.filter==='income'?all.filter(x=>x[3][0]==='+'):s.filter==='expense'?all.filter(x=>x[3][0]==='-'):all;
    return `${head('Financeiro pessoal','Controle suas receitas e despesas')}${toolbar(s)}<div class="ez-stats">${stat('Receitas','R$ 6.500','income','up')}${stat('Despesas','R$ 3.260','expense','down')}${stat('Saldo do mês','R$ 3.240','blue','wallet')}${stat('Assinaturas','R$ 128,90','','target')}</div><div class="ez-tabs"><button data-filter="all" class="${s.filter==='all'?'on':''}">Todas</button><button data-filter="income" class="${s.filter==='income'?'on':''}">Receitas</button><button data-filter="expense" class="${s.filter==='expense'?'on':''}">Despesas</button></div>${rows(filtered)}`;
  }

  function goals(s){return `${head('Metas financeiras','Acompanhe seus objetivos')}${toolbar(s)}<div class="ez-stats">${stat('Total de metas','3','','target')}${stat('Concluídas','1','income','up')}${stat('Valor guardado','R$ 9.020','blue','wallet')}${stat('Falta alcançar','R$ 5.380','expense','down')}</div><section class="ez-card"><div class="ez-card-head"><b>Progresso das metas</b><button data-action="new-goal">+ Nova meta</button></div>${[['Reserva de emergência','R$ 7.400 de R$ 10.000',74],['Quitar cartão','R$ 1.620 de R$ 2.400',68],['Viagem em família','R$ 1.050 de R$ 3.000',35]].map(x=>`<div class="ez-goal" data-goal="${x[0]}"><div class="ez-goal-top"><b>${x[0]}</b><strong>${x[2]}%</strong></div><p>${x[1]}</p><div class="ez-progress"><i style="width:${x[2]}%"></i></div></div>`).join('')}</section>`}

  function business(s){
    const detail=s.mode==='clients'?`<section class="ez-card"><div class="ez-card-head"><b>Produtos e serviços</b><button data-action="new-product">+ Novo</button></div>${rows([['DE','Diagramação editorial','Serviço ativo','+ R$ 850'],['RV','Revisão de texto','Serviço ativo','+ R$ 430']])}</section><section class="ez-card"><div class="ez-card-head"><b>Clientes</b><button data-action="new-client">+ Novo</button></div>${rows([['MA','Mariana Alves','Cliente ativo','+ R$ 1.200'],['CS','Carlos Silva','Cliente ativo','+ R$ 850']])}</section>`:`<section class="ez-card"><div class="ez-card-head"><b>Indicadores</b><button data-focus="clients">Ver clientes</button></div><div class="ez-kpis"><div class="ez-kpi"><span>Ticket médio</span><strong class="positive">R$ 826</strong></div><div class="ez-kpi"><span>Clientes ativos</span><strong>18</strong></div><div class="ez-kpi"><span>ROI</span><strong class="positive">32,4%</strong></div><div class="ez-kpi"><span>Margem líquida</span><strong class="positive">31,0%</strong></div></div><div class="ez-warning">Indicadores atualizados com as movimentações do mês.</div></section><section class="ez-card"><div class="ez-card-head"><b>Fluxo de caixa empresarial</b><button data-view="reports">Abrir relatório</button></div>${chart(s)}</section>`;
    return `${head(s.mode==='clients'?'Clientes e serviços':'Empresa',s.mode==='clients'?'Gestão comercial do seu negócio':'Gestão completa do seu negócio')}${toolbar(s)}<div class="ez-stats">${stat('Receita total','R$ 13.800','income','up')}${stat('Despesas','R$ 9.520','expense','down')}${stat('Lucro','R$ 4.280','blue','wallet')}${stat('Margem','31,0%','','target')}</div>${detail}`;
  }

  function reports(s){const bars=[[40,24],[50,31],[44,35],[63,40],[58,44],[85,59]];return `${head('Relatórios','Análise detalhada das suas finanças')}${toolbar(s)}<div class="ez-tabs"><button data-period="week" class="${s.period==='week'?'on':''}">Semana</button><button data-period="month" class="${s.period==='month'?'on':''}">Mês</button><button data-period="year" class="${s.period==='year'?'on':''}">Ano</button></div><section class="ez-card"><div class="ez-card-head"><b>Receitas × despesas</b><button data-action="export">Exportar PDF</button></div><div class="ez-bars">${bars.map((x,i)=>`<button class="ez-bar" data-tip="R$ ${['1,8','2,4','2,1','3,2','2,8','4,3'][i]} mil"><i class="in" style="height:${x[0]}%"></i><i class="out" style="height:${x[1]}%"></i><small>${['Mar','Abr','Mai','Jun','Jul','Ago'][i]}</small></button>`).join('')}</div><div class="ez-legend"><span><i class="purple"></i>Receitas</span><span><i class="red"></i>Despesas</span></div></section><section class="ez-card"><div class="ez-card-head"><b>Despesas por categoria</b><button data-action="details">Detalhes</button></div><div class="ez-goal"><div class="ez-goal-top"><b>Moradia</b><strong>38%</strong></div><div class="ez-progress"><i style="width:38%"></i></div></div><div class="ez-goal"><div class="ez-goal-top"><b>Alimentação</b><strong>24%</strong></div><div class="ez-progress"><i style="width:24%"></i></div></div></section>`}

  const modal=()=>`<div class="ez-modal-backdrop"><div class="ez-modal"><div class="ez-modal-head"><b>Nova movimentação</b><button data-close aria-label="Fechar">${icon.close}</button></div><div class="ez-field"><label>Descrição</label><div>Venda de serviço</div></div><div class="ez-field"><label>Valor</label><div>R$ 850,00</div></div><div class="ez-field"><label>Categoria</label><div>Serviços</div></div><button class="ez-save" data-save>Salvar demonstração</button></div></div>`;
  function toast(root,msg){root.querySelector('.ez-toast')?.remove();const x=document.createElement('div');x.className='ez-toast';x.textContent=msg;root.appendChild(x);clearTimeout(root._toast);root._toast=setTimeout(()=>x.remove(),1500)}
  function render(root){const s=root._state;const body=s.view==='dashboard'?dashboard(s):s.view==='personal'?personal(s):s.view==='business'?business(s):reports(s);root.innerHTML=`<div class="ez-page">${body}</div>${nav(s.view)}`}
  function bind(root){root.addEventListener('click',e=>{const s=root._state,view=e.target.closest('[data-view]');if(view){s.view=view.dataset.view;s.mode='';render(root);return}const month=e.target.closest('[data-month]');if(month){s.month=Math.max(0,Math.min(2,s.month+Number(month.dataset.month)));render(root);return}const filter=e.target.closest('[data-filter]');if(filter){s.filter=filter.dataset.filter;render(root);return}const period=e.target.closest('[data-period]');if(period){s.period=period.dataset.period;render(root);toast(root,`Período: ${period.textContent}`);return}const dot=e.target.closest('[data-chart]');if(dot){root.querySelector('.ez-tip')?.remove();const tip=document.createElement('span');tip.className='ez-tip';tip.textContent=`Saldo: ${dot.dataset.chart}`;dot.closest('.ez-chart').appendChild(tip);return}const bar=e.target.closest('.ez-bar');if(bar){root.querySelectorAll('.ez-bar').forEach(x=>x.classList.remove('selected'));bar.classList.add('selected');return}const focus=e.target.closest('[data-focus]');if(focus){s.mode=focus.dataset.focus;render(root);return}const row=e.target.closest('[data-row]');if(row){toast(root,`${row.dataset.row} • detalhes abertos`);return}const goal=e.target.closest('[data-goal]');if(goal){toast(root,`${goal.dataset.goal} • progresso atualizado`);return}const action=e.target.closest('[data-action]');if(action){if(action.dataset.action.startsWith('new')){root.insertAdjacentHTML('beforeend',modal());return}toast(root,{details:'Detalhamento aberto',export:'Relatório pronto para exportar'}[action.dataset.action]||'Recurso demonstrativo aberto');return}if(e.target.closest('[data-close]')||e.target.classList.contains('ez-modal-backdrop')){root.querySelector('.ez-modal-backdrop')?.remove();return}if(e.target.closest('[data-save]')){root.querySelector('.ez-modal-backdrop')?.remove();toast(root,'Movimentação adicionada na demonstração')}})}
  const initial=type=>type==='transactions'?{view:'personal',mode:'',month:2,filter:'all',period:'month'}:type==='goals'?{view:'personal',mode:'goals',month:2,filter:'all',period:'month'}:type==='business'?{view:'business',mode:'',month:2,filter:'all',period:'month'}:type==='cashflow'?{view:'reports',mode:'',month:2,filter:'all',period:'month'}:type==='customers'?{view:'business',mode:'clients',month:2,filter:'all',period:'month'}:{view:'dashboard',mode:'',month:2,filter:'all',period:'month'};
  function mount(root,type,hero=false){if(root.dataset.ezapp)return;root.dataset.ezapp='1';root.dataset.hero=hero?'1':'0';root.className='ezapp';root._state=initial(type);bind(root);render(root)}
  function install(){if(!document.querySelector('#ezapp-css')){const s=document.createElement('style');s.id='ezapp-css';s.textContent=css;document.head.appendChild(s)}const hero=[...document.querySelectorAll('p')].find(p=>p.textContent.trim()==='Captura real da tela inicial');if(hero)mount(hero.parentElement,'dashboard',true);const labels=[...document.querySelectorAll('p')].filter(p=>p.textContent.trim()==='Espaço para foto'),types=['dashboard','transactions','goals','business','cashflow','customers'];labels.slice(0,6).forEach((p,i)=>mount(p.parentElement,types[i]));return hero&&labels.length>=6}
  let tries=0;const timer=setInterval(()=>{if(install()||++tries>80)clearInterval(timer)},150);
})();
